const STORAGE_KEY='my-place-map-places-v2';
const GEOCODER='https://nominatim.openstreetmap.org';
const ARCGIS='https://geocode-api.arcgis.com/arcgis/rest/services/World/GeocodeServer/findAddressCandidates';
let places=loadPlaces(),currentLocation=null,activeFilter='all',map,userMarker,userAccuracy,placeMarkers=new Map();
let pickerMap=null,pickerMarker=null,pickerPosition=null;
const els={placeList:document.getElementById('placeList'),countText:document.getElementById('countText'),radius:document.getElementById('radiusSelect'),locate:document.getElementById('locateBtn'),add:document.getElementById('addBtn'),dialog:document.getElementById('placeDialog'),form:document.getElementById('placeForm'),closePlace:document.getElementById('closePlaceBtn'),cancelPlace:document.getElementById('cancelPlaceBtn'),name:document.getElementById('nameInput'),address:document.getElementById('addressInput'),searchAddress:document.getElementById('searchAddressBtn'),addressResults:document.getElementById('addressResults'),pickLocation:document.getElementById('pickLocationBtn'),selectedLocation:document.getElementById('selectedLocation'),category:document.getElementById('categoryInput'),note:document.getElementById('noteInput'),coord:document.getElementById('coordInput'),lat:document.getElementById('latInput'),lng:document.getElementById('lngInput'),want:document.getElementById('wantInput'),error:document.getElementById('formError'),mapHint:document.getElementById('mapHint'),pickerOverlay:document.getElementById('pickerOverlay'),pickerCoords:document.getElementById('pickerCoords'),confirmPicker:document.getElementById('confirmPickerBtn'),closePicker:document.getElementById('closePickerBtn')};
const categoryInfo={food:{icon:'🍜',label:'Ăn uống'},fun:{icon:'🎮',label:'Vui chơi'},cafe:{icon:'☕',label:'Cafe'},other:{icon:'📌',label:'Khác'}};
function validCoord(lat,lng){return Number.isFinite(lat)&&Number.isFinite(lng)&&lat>=-90&&lat<=90&&lng>=-180&&lng<=180}
function parseCoords(text){const m=String(text||'').trim().replace(/\s+/g,' ').match(/^([+-]?(?:\d+(?:\.\d*)?|\.\d+))\s*,\s*([+-]?(?:\d+(?:\.\d*)?|\.\d+))$/);if(!m)return null;const lat=Number(m[1]),lng=Number(m[2]);return validCoord(lat,lng)?{lat,lng}:null}
function syncCoords(lat,lng){if(!validCoord(lat,lng))return false;els.coord.value=`${lat}, ${lng}`;els.lat.value=String(lat);els.lng.value=String(lng);els.selectedLocation.textContent=`📍 Đã chọn: ${lat.toFixed(6)}, ${lng.toFixed(6)}`;return true}
function readCoords(){const c=parseCoords(els.coord.value);if(c){syncCoords(c.lat,c.lng);return c}return null}
function loadPlaces(){try{const raw=localStorage.getItem(STORAGE_KEY);const arr=raw?JSON.parse(raw):[];const seen=new Set();let changed=false;const out=arr.filter(p=>{const key=`${p.name||''}|${Number(p.lat)}|${Number(p.lng)}|${p.address||''}`;if(seen.has(key)){changed=true;return false}seen.add(key);return true});if(changed)localStorage.setItem(STORAGE_KEY,JSON.stringify(out));return out}catch(_){return[]}}
function savePlaces(){localStorage.setItem(STORAGE_KEY,JSON.stringify(places))}
function distanceKm(aLat,aLng,bLat,bLng){const R=6371,p1=aLat*Math.PI/180,p2=bLat*Math.PI/180,dp=(bLat-aLat)*Math.PI/180,dl=(bLng-aLng)*Math.PI/180,x=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*R*Math.asin(Math.sqrt(x))}
function filteredPlaces(){const radius=Number(els.radius.value);return places.map(p=>({...p,distance:currentLocation?distanceKm(currentLocation.lat,currentLocation.lng,p.lat,p.lng):null})).filter(p=>{if(activeFilter==='want'&&!p.want)return false;if(['food','fun','cafe'].includes(activeFilter)&&p.category!==activeFilter)return false;if(currentLocation&&radius<999&&p.distance>radius)return false;return true}).sort((a,b)=>a.distance!=null&&b.distance!=null?a.distance-b.distance:b.createdAt-a.createdAt)}
function escapeHtml(v){return String(v??'').replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]))}
function openDirections(lat,lng){window.open(`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(`${lat},${lng}`)}`,'_blank','noopener')}
function renderMarkers(data){placeMarkers.forEach(m=>m.remove());placeMarkers.clear();data.forEach(p=>{if(!validCoord(Number(p.lat),Number(p.lng)))return;const icon=categoryInfo[p.category]?.icon||'📌',marker=L.marker([p.lat,p.lng]).addTo(map);marker.bindPopup(`<div class="popup"><strong>${icon} ${escapeHtml(p.name)}</strong><div>${escapeHtml(categoryInfo[p.category]?.label||'Khác')}</div>${p.address?`<div>📍 ${escapeHtml(p.address)}</div>`:''}${p.note?`<p>${escapeHtml(p.note)}</p>`:''}${p.want?'<span>❤️ Muốn đi</span>':''}<br><button class="popup-direction" data-lat="${p.lat}" data-lng="${p.lng}">🧭 Chỉ đường</button></div>`);marker.on('popupopen',e=>{const b=e.popup.getElement()?.querySelector('.popup-direction');if(b)b.onclick=()=>openDirections(Number(b.dataset.lat),Number(b.dataset.lng))});placeMarkers.set(p.id,marker)})}
function render(){const data=filteredPlaces();els.countText.textContent=`${data.length} địa điểm`;els.placeList.innerHTML='';renderMarkers(data);if(!data.length){els.placeList.innerHTML='<div class="empty">Chưa có địa điểm phù hợp. Bấm <b>＋ Thêm địa điểm</b> hoặc nhấp đúp trên bản đồ để lưu.</div>';return}data.forEach(p=>{const icon=categoryInfo[p.category]?.icon||'📌',dist=p.distance==null?'Chưa xác định khoảng cách':`${p.distance.toFixed(1)} km từ bạn`,card=document.createElement('article');card.className='place-card';card.id=`place-${p.id}`;card.innerHTML=`<div class="place-title">${icon} ${escapeHtml(p.name)}</div><div class="place-meta">${escapeHtml(categoryInfo[p.category]?.label||'Khác')} · ${dist}</div>${p.address?`<div class="place-address">📍 ${escapeHtml(p.address)}</div>`:''}${p.note?`<div class="place-note">${escapeHtml(p.note)}</div>`:''}${p.want?'<span class="badge">❤️ Muốn đi</span>':''}<div class="card-actions"><button type="button" class="secondary show-place" data-id="${p.id}">📍 Xem trên bản đồ</button><button type="button" class="secondary open-map" data-lat="${p.lat}" data-lng="${p.lng}">🧭 Chỉ đường</button><button type="button" class="secondary delete-place" data-id="${p.id}">Xóa</button></div>`;els.placeList.appendChild(card)});els.placeList.querySelectorAll('.show-place').forEach(b=>b.onclick=()=>{const p=places.find(x=>x.id===b.dataset.id);if(p){map.setView([p.lat,p.lng],18,{animate:true});placeMarkers.get(p.id)?.openPopup()}});els.placeList.querySelectorAll('.open-map').forEach(b=>b.onclick=()=>openDirections(Number(b.dataset.lat),Number(b.dataset.lng)));els.placeList.querySelectorAll('.delete-place').forEach(b=>b.onclick=()=>{places=places.filter(p=>p.id!==b.dataset.id);savePlaces();render()})}
function initMap(){map=L.map('map',{zoomControl:true}).setView([10.7769,106.7009],13);window.__myPlaceMapMain=map;L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);map.doubleClickZoom.disable();map.on('dblclick',e=>{L.DomEvent.stop(e);openAddDialog(e.latlng.lat,e.latlng.lng);reverseGeocode(e.latlng.lat,e.latlng.lng,true)})}
async function nominatimSearch(q){const u=new URL(`${GEOCODER}/search`);u.searchParams.set('format','jsonv2');u.searchParams.set('limit','8');u.searchParams.set('countrycodes','vn');u.searchParams.set('addressdetails','1');u.searchParams.set('q',q);const r=await fetch(u,{headers:{Accept:'application/json'}});if(!r.ok)throw Error();return r.json()}
async function arcgisSearch(q){const u=new URL(ARCGIS);u.searchParams.set('SingleLine',q);u.searchParams.set('f','json');u.searchParams.set('maxLocations','8');u.searchParams.set('outFields','*');const r=await fetch(u);if(!r.ok)throw Error();const d=await r.json();return(d.candidates||[]).map(x=>({display_name:x.address,lat:Number(x.location?.y),lon:Number(x.location?.x)})).filter(x=>validCoord(x.lat,x.lon))}
function renderSearchResult(title,onClick){const b=document.createElement('button');b.type='button';b.className='address-result';b.textContent=title;b.onclick=onClick;els.addressResults.appendChild(b)}
async function searchAddress(){const q=els.address.value.trim();els.error.textContent='';els.addressResults.innerHTML='';if(!q){els.error.textContent='Hãy nhập địa chỉ cần tìm.';return}els.searchAddress.disabled=true;els.searchAddress.textContent='⌛ Đang tìm...';try{let results=[];try{results=await nominatimSearch(q)}catch(_){}if(!results.length){try{results=await arcgisSearch(q)}catch(_){} }if(!results.length){els.addressResults.innerHTML='<div class="address-no-result">Không tìm thấy địa chỉ. Hãy thử viết ngắn hơn, ví dụ “450/3 Phan Xích Long, Hồ Chí Minh”, hoặc dán tọa độ Google Maps.</div>';return}results.forEach(r=>{const lat=Number(r.lat),lng=Number(r.lon);renderSearchResult(r.display_name,()=>{els.address.value=r.display_name;syncCoords(lat,lng);els.addressResults.innerHTML='';map.setView([lat,lng],18,{animate:true});els.mapHint.textContent='📍 Đã chọn kết quả tìm kiếm. Nếu cần đúng vị trí số nhà, dán tọa độ Google Maps.'})})}catch(_){els.error.textContent='Không thể tìm địa chỉ lúc này. M vẫn có thể dán tọa độ Google Maps.'}finally{els.searchAddress.disabled=false;els.searchAddress.textContent='🔎 Tìm địa chỉ'}}
async function reverseGeocode(lat,lng,fill=false){try{const u=new URL(`${GEOCODER}/reverse`);u.searchParams.set('format','jsonv2');u.searchParams.set('lat',lat);u.searchParams.set('lon',lng);u.searchParams.set('zoom','18');u.searchParams.set('addressdetails','1');const r=await fetch(u,{headers:{Accept:'application/json'}});const d=await r.json();if(fill&&d.display_name)els.address.value=d.display_name;return d.display_name||''}catch(_){return''}}
function openAddDialog(lat=null,lng=null){els.error.textContent='';els.addressResults.innerHTML='';els.name.value='';els.address.value='';els.note.value='';els.coord.value='';els.lat.value='';els.lng.value='';els.selectedLocation.textContent='Chưa chọn vị trí chính xác';els.want.checked=false;els.category.value='food';if(validCoord(lat,lng))syncCoords(lat,lng);els.dialog.showModal();setTimeout(()=>els.name.focus(),50)}
function closePlaceDialog(){if(els.dialog.open)els.dialog.close();els.error.textContent='';els.addressResults.innerHTML=''}
function setPickerPosition(lat,lng){if(!validCoord(lat,lng))return;pickerPosition={lat,lng};if(pickerMarker)pickerMarker.setLatLng([lat,lng]);else{pickerMarker=L.marker([lat,lng],{draggable:true}).addTo(pickerMap);pickerMarker.on('dragend',()=>{const p=pickerMarker.getLatLng();setPickerPosition(p.lat,p.lng)})}els.pickerCoords.textContent=`📍 ${lat.toFixed(6)}, ${lng.toFixed(6)}`}
function openPicker(){const c=readCoords(),center=c||(map?map.getCenter():{lat:10.7769,lng:106.7009});els.dialog.close();els.pickerOverlay.hidden=false;if(!pickerMap){pickerMap=L.map('pickerMap',{zoomControl:true,doubleClickZoom:false}).setView([center.lat,center.lng],18);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:20,attribution:'&copy; OpenStreetMap contributors'}).addTo(pickerMap);pickerMap.on('click',e=>setPickerPosition(e.latlng.lat,e.latlng.lng))}setTimeout(()=>{pickerMap.invalidateSize();pickerMap.setView([center.lat,center.lng],18);setPickerPosition(center.lat,center.lng)},100)}
function closePicker(){els.pickerOverlay.hidden=true;if(!els.dialog.open)els.dialog.showModal()}
async function confirmPicker(){if(!pickerPosition){els.pickerCoords.textContent='⚠️ Hãy chọn vị trí trên bản đồ.';return}const{lat,lng}=pickerPosition;syncCoords(lat,lng);const a=await reverseGeocode(lat,lng);if(a)els.address.value=a;closePicker();els.mapHint.textContent='🎯 Đã chọn vị trí chính xác. Bấm Lưu địa điểm.'}
function savePlace(e){e.preventDefault();els.error.textContent='';const name=els.name.value.trim(),c=readCoords();if(!name){els.error.textContent='Hãy nhập tên địa điểm.';return}if(!c){els.error.textContent='Hãy dán tọa độ theo dạng: Vĩ độ, Kinh độ (ví dụ 10.800829838769747, 106.68482208597538).';return}const address=els.address.value.trim();const duplicate=places.some(p=>p.name.trim().toLowerCase()===name.toLowerCase()&&Math.abs(Number(p.lat)-c.lat)<1e-12&&Math.abs(Number(p.lng)-c.lng)<1e-12&&String(p.address||'').trim()===address);if(duplicate){els.error.textContent='Địa điểm này đã tồn tại.';return}places.push({id:window.crypto?.randomUUID?.()||`${Date.now()}-${Math.random()}`,name,address,category:els.category.value,note:els.note.value.trim(),lat:c.lat,lng:c.lng,want:els.want.checked,createdAt:Date.now()});savePlaces();els.radius.value='999';closePlaceDialog();render();map.setView([c.lat,c.lng],18,{animate:true});els.mapHint.textContent='📍 Đã lưu địa điểm tại đúng tọa độ Google Maps.'}
function setCurrentLocation(lat,lng,accuracy){currentLocation={lat,lng};if(userMarker)userMarker.setLatLng([lat,lng]);else userMarker=L.circleMarker([lat,lng],{radius:8,color:'#fff',weight:3,fillColor:'#1976d2',fillOpacity:1}).addTo(map).bindTooltip('Vị trí của bạn');if(userAccuracy)userAccuracy.remove();if(accuracy>0)userAccuracy=L.circle([lat,lng],{radius:accuracy,color:'#1976d2',weight:1,fillOpacity:.08}).addTo(map);map.setView([lat,lng],15);els.mapHint.textContent='📍 Đã xác định vị trí của bạn. Nhấp đúp trên bản đồ để thêm địa điểm.';render()}
function useLocation(){if(!navigator.geolocation){els.mapHint.textContent='Trình duyệt không hỗ trợ định vị.';return}els.locate.disabled=true;els.locate.textContent='⌛ Đang định vị...';navigator.geolocation.getCurrentPosition(p=>{setCurrentLocation(p.coords.latitude,p.coords.longitude,p.coords.accuracy);els.locate.disabled=false;els.locate.textContent='📍 Vị trí của tôi'},()=>{els.mapHint.textContent='⚠️ Chưa được cấp quyền vị trí. Bạn vẫn có thể dùng bản đồ.';els.locate.disabled=false;els.locate.textContent='📍 Vị trí của tôi';render()},{enableHighAccuracy:true,timeout:12000,maximumAge:60000})}
els.add.onclick=()=>openAddDialog();els.closePlace.onclick=closePlaceDialog;els.cancelPlace.onclick=closePlaceDialog;els.searchAddress.onclick=searchAddress;els.address.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();searchAddress()}};els.coord.oninput=()=>{const c=parseCoords(els.coord.value);if(c){syncCoords(c.lat,c.lng);els.error.textContent='';map.setView([c.lat,c.lng],18,{animate:true})}};els.pickLocation.onclick=openPicker;els.closePicker.onclick=closePicker;els.confirmPicker.onclick=confirmPicker;els.form.onsubmit=savePlace;els.locate.onclick=useLocation;els.radius.onchange=render;document.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{document.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');activeFilter=b.dataset.filter;render()});initMap();render();useLocation();
