const STORAGE_KEY='my-place-map-places-v2';
const GEOCODER='https://nominatim.openstreetmap.org';
let places=loadPlaces(),currentLocation=null,activeFilter='all',map,userMarker,userAccuracy,placeMarkers=new Map();
let pickerMap,pickerMarker,pickerPosition=null;
const els={
 placeList:document.getElementById('placeList'),countText:document.getElementById('countText'),radius:document.getElementById('radiusSelect'),locate:document.getElementById('locateBtn'),add:document.getElementById('addBtn'),dialog:document.getElementById('placeDialog'),form:document.getElementById('placeForm'),name:document.getElementById('nameInput'),address:document.getElementById('addressInput'),searchAddress:document.getElementById('searchAddressBtn'),addressResults:document.getElementById('addressResults'),pickLocation:document.getElementById('pickLocationBtn'),selectedLocation:document.getElementById('selectedLocation'),category:document.getElementById('categoryInput'),note:document.getElementById('noteInput'),lat:document.getElementById('latInput'),lng:document.getElementById('lngInput'),want:document.getElementById('wantInput'),error:document.getElementById('formError'),mapHint:document.getElementById('mapHint'),pickerOverlay:document.getElementById('pickerOverlay'),pickerMap:document.getElementById('pickerMap'),pickerCoords:document.getElementById('pickerCoords'),confirmPicker:document.getElementById('confirmPickerBtn'),closePicker:document.getElementById('closePickerBtn')};
const categoryInfo={food:{icon:'🍜',label:'Ăn uống'},fun:{icon:'🎮',label:'Vui chơi'},cafe:{icon:'☕',label:'Cafe'},other:{icon:'📌',label:'Khác'}};
function loadPlaces(){try{const raw=localStorage.getItem(STORAGE_KEY);return raw?JSON.parse(raw):[]}catch(_){return[]}}
function savePlaces(){localStorage.setItem(STORAGE_KEY,JSON.stringify(places))}
function validCoord(lat,lng){return Number.isFinite(lat)&&Number.isFinite(lng)&&lat>=-90&&lat<=90&&lng>=-180&&lng<=180}
function distanceKm(aLat,aLng,bLat,bLng){const R=6371,p1=aLat*Math.PI/180,p2=bLat*Math.PI/180,dp=(bLat-aLat)*Math.PI/180,dl=(bLng-aLng)*Math.PI/180,x=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*R*Math.asin(Math.sqrt(x))}
function filteredPlaces(){const radius=Number(els.radius.value);return places.map(p=>({...p,distance:currentLocation?distanceKm(currentLocation.lat,currentLocation.lng,p.lat,p.lng):null})).filter(p=>{if(activeFilter==='want'&&!p.want)return false;if(['food','fun','cafe'].includes(activeFilter)&&p.category!==activeFilter)return false;if(currentLocation&&radius<999&&p.distance>radius)return false;return true}).sort((a,b)=>a.distance!=null&&b.distance!=null?a.distance-b.distance:b.createdAt-a.createdAt)}
function initMap(){map=L.map('map',{zoomControl:true}).setView([10.7769,106.7009],13);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);map.on('click',async e=>{openAddDialog(e.latlng.lat,e.latlng.lng);await reverseGeocode(e.latlng.lat,e.latlng.lng,true)})}
function renderMarkers(data){placeMarkers.forEach(m=>m.remove());placeMarkers.clear();data.forEach(p=>{const icon=categoryInfo[p.category]?.icon||'📌',marker=L.marker([p.lat,p.lng]).addTo(map);marker.bindPopup(`<div class="popup"><strong>${icon} ${escapeHtml(p.name)}</strong><div>${escapeHtml(categoryInfo[p.category]?.label||'Khác')}</div>${p.address?`<div>📍 ${escapeHtml(p.address)}</div>`:''}${p.note?`<p>${escapeHtml(p.note)}</p>`:''}${p.want?'<span>❤️ Muốn đi</span>':''}<br><button class="popup-direction" data-lat="${p.lat}" data-lng="${p.lng}">🧭 Chỉ đường</button></div>`);marker.on('popupopen',e=>{const btn=e.popup.getElement()?.querySelector('.popup-direction');if(btn)btn.addEventListener('click',()=>openDirections(Number(btn.dataset.lat),Number(btn.dataset.lng)))});placeMarkers.set(p.id,marker)})}
function render(){const data=filteredPlaces();els.countText.textContent=`${data.length} địa điểm`;els.placeList.innerHTML='';renderMarkers(data);if(!data.length){els.placeList.innerHTML='<div class="empty">Chưa có địa điểm phù hợp. Bấm <b>＋ Thêm địa điểm</b> hoặc bấm một điểm trên bản đồ để lưu.</div>';return}data.forEach(p=>{const icon=categoryInfo[p.category]?.icon||'📌',metaDistance=p.distance==null?'Chưa xác định khoảng cách':`${p.distance.toFixed(1)} km từ bạn`,want=p.want?'<span class="badge">❤️ Muốn đi</span>':'';const card=document.createElement('article');card.className='place-card';card.id=`place-${p.id}`;card.innerHTML=`<div class="place-title">${icon} ${escapeHtml(p.name)}</div><div class="place-meta">${escapeHtml(categoryInfo[p.category]?.label||'Khác')} · ${metaDistance}</div>${p.address?`<div class="place-address">📍 ${escapeHtml(p.address)}</div>`:''}${p.note?`<div class="place-note">${escapeHtml(p.note)}</div>`:''}${want}<div class="card-actions"><button type="button" class="secondary show-place" data-id="${p.id}">📍 Xem trên bản đồ</button><button type="button" class="secondary open-map" data-lat="${p.lat}" data-lng="${p.lng}">🧭 Chỉ đường</button><button type="button" class="secondary delete-place" data-id="${p.id}">Xóa</button></div>`;els.placeList.appendChild(card)});els.placeList.querySelectorAll('.show-place').forEach(btn=>btn.addEventListener('click',()=>{const p=places.find(x=>x.id===btn.dataset.id);if(!p)return;map.setView([p.lat,p.lng],Math.max(map.getZoom(),16),{animate:true});placeMarkers.get(p.id)?.openPopup()}));els.placeList.querySelectorAll('.delete-place').forEach(btn=>btn.addEventListener('click',()=>{places=places.filter(p=>p.id!==btn.dataset.id);savePlaces();render()}));els.placeList.querySelectorAll('.open-map').forEach(btn=>btn.addEventListener('click',()=>openDirections(Number(btn.dataset.lat),Number(btn.dataset.lng))))}
function openDirections(lat,lng){window.open(`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(`${lat},${lng}`)}`,'_blank','noopener')}
function escapeHtml(value){return String(value).replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]))}
async function nominatim(path,params){const url=new URL(`${GEOCODER}${path}`);Object.entries(params).forEach(([k,v])=>url.searchParams.set(k,v));const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),10000);try{const res=await fetch(url.toString(),{signal:controller.signal,headers:{Accept:'application/json'}});if(!res.ok)throw new Error('Geocoding failed');return await res.json()}finally{clearTimeout(timer)}}
async function searchAddress(){const q=els.address.value.trim();els.error.textContent='';els.addressResults.innerHTML='';if(!q){els.error.textContent='Hãy nhập địa chỉ cần tìm.';return}els.searchAddress.disabled=true;els.searchAddress.textContent='⌛ Đang tìm...';try{const results=await nominatim('/search',{format:'jsonv2',limit:'5',countrycodes:'vn',q});if(!results.length){els.addressResults.innerHTML='<div class="address-no-result">Không tìm thấy địa chỉ. Thử nhập thêm quận/huyện hoặc thành phố.</div>';return}results.forEach(r=>{const btn=document.createElement('button');btn.type='button';btn.className='address-result';btn.textContent=r.display_name;btn.addEventListener('click',()=>selectAddress(r));els.addressResults.appendChild(btn)})}catch(e){els.error.textContent='Không thể tìm địa chỉ lúc này. Kiểm tra mạng rồi thử lại.'}finally{els.searchAddress.disabled=false;els.searchAddress.textContent='🔎 Tìm địa chỉ'}}
function selectAddress(result){const lat=Number(result.lat),lng=Number(result.lon);if(!validCoord(lat,lng))return;els.address.value=result.display_name;setCoordinates(lat,lng);els.addressResults.innerHTML='';map.setView([lat,lng],17,{animate:true});els.mapHint.textContent='📍 Đã chọn địa chỉ gần đúng. Nếu cần chính xác đến đúng số nhà/vị trí quán, bấm “🎯 Chọn chính xác trên bản đồ”.'}
function setCoordinates(lat,lng){els.lat.value=lat.toFixed(6);els.lng.value=lng.toFixed(6);els.selectedLocation.textContent=`📍 Đã chọn: ${lat.toFixed(6)}, ${lng.toFixed(6)}`}
async function reverseGeocode(lat,lng,fillForm=false){try{const result=await nominatim('/reverse',{format:'jsonv2',lat:String(lat),lon:String(lng),zoom:'18',addressdetails:'1'});if(fillForm&&result.display_name)els.address.value=result.display_name;return result?.display_name||''}catch(_){return''}}
function initPicker(){pickerMap=L.map('pickerMap',{zoomControl:true}).setView(currentLocation?[currentLocation.lat,currentLocation.lng]:[10.7769,106.7009],16);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:20,attribution:'&copy; OpenStreetMap contributors'}).addTo(pickerMap);pickerMap.on('click',e=>setPickerPosition(e.latlng.lat,e.latlng.lng));}
function setPickerPosition(lat,lng){pickerPosition={lat,lng};if(pickerMarker)pickerMarker.setLatLng([lat,lng]);else pickerMarker=L.marker([lat,lng],{draggable:true}).addTo(pickerMap);pickerMarker.on('dragend',()=>{const p=pickerMarker.getLatLng();setPickerPosition(p.lat,p.lng)});els.pickerCoords.textContent=`📍 ${lat.toFixed(6)}, ${lng.toFixed(6)}`}
function openPicker(){els.pickerOverlay.hidden=false;pickerPosition=validCoord(Number(els.lat.value),Number(els.lng.value))?{lat:Number(els.lat.value),lng:Number(els.lng.value)}:(currentLocation?{...currentLocation}:null);if(!pickerMap)initPicker();setTimeout(()=>{pickerMap.invalidateSize();if(pickerPosition){pickerMap.setView([pickerPosition.lat,pickerPosition.lng],18);setPickerPosition(pickerPosition.lat,pickerPosition.lng)}},50);els.pickerCoords.textContent=pickerPosition?`📍 ${pickerPosition.lat.toFixed(6)}, ${pickerPosition.lng.toFixed(6)}`:'Bấm vào bản đồ để chọn vị trí'}
function closePicker(){els.pickerOverlay.hidden=true}
async function confirmPicker(){if(!pickerPosition){els.error.textContent='Hãy bấm lên bản đồ để chọn vị trí.';return}setCoordinates(pickerPosition.lat,pickerPosition.lng);const address=await reverseGeocode(pickerPosition.lat,pickerPosition.lng);if(address)els.address.value=address;closePicker();els.mapHint.textContent='🎯 Đã chọn đúng vị trí trên bản đồ. Bấm Lưu địa điểm để hoàn tất.'}
function setCurrentLocation(lat,lng,accuracy=0){currentLocation={lat,lng};if(userMarker)userMarker.setLatLng([lat,lng]);else userMarker=L.circleMarker([lat,lng],{radius:8,color:'#fff',weight:3,fillColor:'#1976d2',fillOpacity:1}).addTo(map).bindTooltip('Vị trí của bạn');if(userAccuracy)userAccuracy.remove();if(accuracy>0)userAccuracy=L.circle([lat,lng],{radius:accuracy,color:'#1976d2',weight:1,fillOpacity:.08}).addTo(map);map.setView([lat,lng],15,{animate:true});els.mapHint.textContent='📍 Đã xác định vị trí của bạn. Bấm lên bản đồ để thêm địa điểm.';els.locate.disabled=false;els.locate.textContent='📍 Vị trí của tôi';render()}
function useLocation(){if(!navigator.geolocation){els.mapHint.textContent='Trình duyệt không hỗ trợ định vị. Bạn vẫn có thể dùng bản đồ và nhập địa chỉ.';return}els.locate.disabled=true;els.locate.textContent='⌛ Đang định vị...';navigator.geolocation.getCurrentPosition(pos=>setCurrentLocation(pos.coords.latitude,pos.coords.longitude,pos.coords.accuracy),()=>{els.mapHint.textContent='⚠️ Chưa được cấp quyền vị trí. Hãy bật Location cho trang này rồi bấm “Vị trí của tôi”.';els.locate.disabled=false;els.locate.textContent='📍 Vị trí của tôi';render()},{enableHighAccuracy:true,timeout:12000,maximumAge:60000})}
function openAddDialog(lat=null,lng=null){els.error.textContent='';els.addressResults.innerHTML='';els.name.value='';els.address.value='';els.note.value='';els.lat.value=lat!=null?Number(lat).toFixed(6):(currentLocation?currentLocation.lat.toFixed(6):'');els.lng.value=lng!=null?Number(lng).toFixed(6):(currentLocation?currentLocation.lng.toFixed(6):'');els.selectedLocation.textContent=lat!=null&&lng!=null?`📍 Đã chọn: ${Number(lat).toFixed(6)}, ${Number(lng).toFixed(6)}`:'Chưa chọn vị trí chính xác';els.want.checked=false;els.category.value='food';els.dialog.showModal();setTimeout(()=>els.name.focus(),50)}
els.locate.addEventListener('click',useLocation);els.radius.addEventListener('change',render);els.add.addEventListener('click',()=>openAddDialog());els.searchAddress.addEventListener('click',searchAddress);els.address.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();searchAddress()}});els.pickLocation.addEventListener('click',openPicker);els.closePicker.addEventListener('click',closePicker);els.confirmPicker.addEventListener('click',confirmPicker);
els.form.addEventListener('submit',event=>{event.preventDefault();const lat=Number(els.lat.value),lng=Number(els.lng.value);if(!els.name.value.trim()){els.error.textContent='Hãy nhập tên địa điểm.';return}if(!validCoord(lat,lng)){els.error.textContent='Hãy nhập địa chỉ và chọn vị trí trên bản đồ.';return}places.push({id:crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random()}`,name:els.name.value.trim(),address:els.address.value.trim(),category:els.category.value,note:els.note.value.trim(),lat,lng,want:els.want.checked,createdAt:Date.now()});savePlaces();els.dialog.close();render();const saved=places[places.length-1];map.setView([saved.lat,saved.lng],16,{animate:true});setTimeout(()=>placeMarkers.get(saved.id)?.openPopup(),350)});
document.querySelectorAll('.chip').forEach(chip=>chip.addEventListener('click',()=>{document.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));chip.classList.add('active');activeFilter=chip.dataset.filter;render()}));
initMap();render();useLocation();
